services:
  - type: web
    name: apex-pos-api
    env: node
    repo: https://github.com/xsoly1-boop/PDV.git
    region: oregon
    branch: main
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.backup.prisma && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: DIRECT_URL
        fromSecret: DIRECT_URL
    plan: starter

  - type: static
    name: apex-pos-web
    env: node
    repo: https://github.com/xsoly1-boop/PDV.git
    region: oregon
    branch: main
    rootDir: apps/pos-desktop
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars: []
    plan: starter
