// Tipos compartidos — inlined directamente para evitar problemas de resolución en producción

export enum Rol {
  ADMINISTRADOR = 'ADMINISTRADOR',
  GERENTE = 'GERENTE',
  CAJERO = 'CAJERO',
  VENDEDOR_MOVIL = 'VENDEDOR_MOVIL'
}

export enum TipoMovimiento {
  ENTRADA_COMPRA = 'ENTRADA_COMPRA',
  ENTRADA_TRASPASO = 'ENTRADA_TRASPASO',
  ENTRADA_DEVOLUCION = 'ENTRADA_DEVOLUCION',
  ENTRADA_AJUSTE = 'ENTRADA_AJUSTE',
  SALIDA_VENTA = 'SALIDA_VENTA',
  SALIDA_TRASPASO = 'SALIDA_TRASPASO',
  SALIDA_MERMA = 'SALIDA_MERMA',
  SALIDA_AJUSTE = 'SALIDA_AJUSTE'
}

export enum EstadoReserva {
  ACTIVA = 'ACTIVA',
  COMPLETADA = 'COMPLETADA',
  EXPIRADA = 'EXPIRADA',
  CANCELADA = 'CANCELADA'
}

export enum EstadoTraspaso {
  EN_TRANSITO = 'EN_TRANSITO',
  COMPLETADO = 'COMPLETADO',
  COMPLETADO_PARCIAL = 'COMPLETADO_PARCIAL',
  CANCELADO = 'CANCELADO'
}

export enum Giro {
  ABARROTES = 'ABARROTES',
  FARMACIA = 'FARMACIA',
  FERRETERIA = 'FERRETERIA',
  REFACCIONARIA = 'REFACCIONARIA'
}
